# Generated by Django 3.1.7 on 2021-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about-image/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='Rasm teksti')),
                ('about_text', models.TextField(verbose_name='Malumot')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=14, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home-image/', verbose_name='Assosiy rasm')),
                ('caption', models.CharField(blank=True, max_length=400, null=True, verbose_name='Rasm teksti')),
            ],
        ),
    ]
