# Generated by Django 3.1.7 on 2021-03-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Kampaniya Haqida', 'verbose_name_plural': 'Kampaniya Haqida'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='homepicture',
            options={'verbose_name': 'Assosiy Rasm', 'verbose_name_plural': 'Assosiy Rasmlar'},
        ),
    ]
