# Generated by Django 3.1.7 on 2021-03-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210325_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Habar'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz Ismi'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefon Raqami'),
        ),
    ]
