# Generated by Django 3.1.7 on 2021-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210329_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='homepicture',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Aktiv Rasm'),
        ),
    ]
