# Generated by Django 3.1.7 on 2021-03-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210323_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
