# Generated by Django 3.1.7 on 2021-03-29 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210324_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rasm Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category-image/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Kategoriya Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='product.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_toshkent',
            field=models.BooleanField(default=False, verbose_name="Toshkent bo'ylab yetkazib berish"),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_uzb',
            field=models.BooleanField(default=False, verbose_name="O'zbekiston bo'ylab yetkazib berish"),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Tarifi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=100, unique=True, verbose_name='Maxsulot Modeli'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rasm Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product-image/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product', verbose_name='Maxsulot'),
        ),
    ]
