# Generated by Django 3.1.7 on 2021-03-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210329_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product-image/', verbose_name='Rasmlar'),
        ),
    ]
